# Generated by Django 2.2.20 on 2021-04-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_id', models.IntegerField()),
                ('E_name', models.TextField(max_length=30)),
                ('E_mail_add', models.EmailField(max_length=254)),
                ('E_sal', models.FloatField()),
                ('E_sal_date', models.DateTimeField()),
            ],
        ),
    ]
